print("안녕하세요~! 다음 질문에 답하고 이야기를 완성하세요.")
print()
animal = input("동물을 입력하세요: ")
name = input("이름을 입력하세요: ")
color1 = input("색상1을 입력하세요: ")
color2 = input("색상2을 입력하세요: ")
print("저의 반려동물은", animal  ,"이며, 이름은 "+name+"입니다.")
print("색은 "+color1+", "+color2+"이며 곰과 입니다.")
print("음식은 대나무 죽순을 먹습니다.")
print("지금 밖이 시끄럽습니다.")